### ISSUE TITLE
Lost BNB when sell token

### ISSUE THREAD

**Issue by cuongnguyengit** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#18]
Hi,

I had an issue when i sold drace token.
My tx: https://bscscan.com/tx/0xb252923423b57f08f93d59f14e3cc001fea272d425735ae3e17adad6892921a3

What happend for my metamask account?

**Comment by cuongnguyengit** [comment]
Please make me what happened? I can't understand this

**Comment by cuongnguyengit** [comment]
my transaction was successfully completed but it seems my funds redirected to another address (0x7437122D8E2Cf47326cB341bc2C357a3324c14eD).
It seems your project is a joke

**Comment by Trading-Tiger** [comment]
Cheeky to call us a joke, although they have not correctly made their research.
The bot buys with BNB......

Check which pool you sold your tokens to:
https://bscscan.com/address/0x68eA0FC62f7F9A148b73B44A135753133CcC72b6
The main pool of this token is with BUSD.

**Comment by cuongnguyengit** [comment]
I'm sorry but i can't understand, please explain for me. 
What's wrong in my transaction?

**Comment by cuongnguyengit** [comment]
Does Drace have no pair contract with BNB?

**Comment by cuongnguyengit** [comment]
I swapped Drace in PancakeSwap.
Then I had Drace in my wallet and i sold them with address: 0xa6c897caaca3db7fd6e2d2ce1a00744f40ab87bb by the bot.
Please make me if i lost my money because of my idiot.
i'm really confused @Trading-Tiger

**Comment by Trading-Tiger** [comment]
You have not looked correctly, look at Poocoin your token, especially the LP pools.

There is nothing wrong in your transaction, PancakeSwap automatically routs to the largest pool, our bot does not do that, it only buys with BNB!

Your Drace token has a BNB pool, but this is extremely small, because your sum was larger than the pool size, there was high slippage, which is calculated by Contract to make sniping possible even with high price fluctuations.

**Comment by cuongnguyengit** [comment]
Oh i knew a bit more. So my bnb is real non exist. 
What can I do to take my refund?
Additionally, how need I do to transact securely with your bot?

Thank you.

**Comment by Trading-Tiger** [comment]
If your BNB would been stuck on our contract, I would sent them back to you, but your BNB stayed in the LP pool as a reward for the LP staker.
Here is no possibility to refund these BNB, sorry!

Yes, it has now gone stupid, some users wished the function of the --sellonly, so now this problem has arisen, I will still write a few notes in the tools/readme, so that such a thing in the future no one more happens.

**Comment by cuongnguyengit** [comment]
Sorry, I understood that my bnb is not at you.
Really I didn't use app, I customized your source code but I not understand blockchain. 

I think snip and buyonly function is safe now. 
I had an experience for me. Although, I think that we need check any condition to secure transactions.


Thank you.

**Comment by Trading-Tiger** [comment]
Hi,
So, I have worked all afternoon on a solution, now our contract automatically finds the LP with the most tokens and uses the basecurrency e.g. BUSD or USDT.

With BNB he then buys BUSD and buys their token,
or the other way : he sells the token to Busd and Busd then to BNB these are then sent to them.

https://bscscan.com/tx/0xd9a58a04c22e1d344020ab2ab935aa8b40eb8554fa95e9d36ed8c6f961a2165e
https://bscscan.com/tx/0x62dffb1698c56096e1dce51a99b67e419213116da5664ff1389f19750c7d02c3

Thank you,
and good luck!

**Comment by Trading-Tiger** [comment]
Hey,
no problem at all, we have it handled now and found a solution.

Yes Pancakeswap does it almost the same, only they do it via website, with JavaScript.
At Trading-Tigers it is done by the smart contract.

I would be delighted to see reviews and transactions, Thank you!

**Comment by cuongnguyengit** [comment]
what change in commit 4887743?
Can u explain for me?

Thanks.

**Comment by cuongnguyengit** [comment]
I had lost all my token 

0x10442e208F743911ab5cE501764923DD976aA965
 
How had i been hacked ?

**Comment by cuongnguyengit** [comment]
Can you help me?
